"""empty message

Revision ID: f50031dcc8eb
Revises: 1be756343562
Create Date: 2022-09-20 17:28:47.837216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50031dcc8eb'
down_revision = '1be756343562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_business_uc', 'likes', ['user_id', 'business_id'])
    op.create_foreign_key(None, 'menu_items', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.drop_constraint('_user_business_uc', 'likes', type_='unique')
    # ### end Alembic commands ###
